replicaCount: 1

image:
  repository: orders-api
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 8080

postgres:
  host: postgres
  port: "5432"
  database: fiap_games
  username: orders_role
  searchPath: orders

catalog:
  baseUrl: "http://catalog-api:8080"
